spring.application.name=assessment
server.port=${PORT:8080}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${LOCAL_DATASOURCE_URL:jdbc:mysql://localhost:3306/performance_assessment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Manila}
spring.datasource.username=${LOCAL_DATASOURCE_USERNAME:root}
spring.datasource.password=${LOCAL_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
